### ISSUE TITLE
[BUG] FluxBench reported the same Ip that was already in use

### ISSUE THREAD

**Issue by hostingnuggets** [RunOnFlux/flux#912]
**Describe the bug**

Hello since this night at 02:59 CET my Flux cumulus node is not working anymore and the status of my Flux node is now on "expired". I did not change anything on my network neither on my node, there was not even an internet interruption, so I really don't understand what has happened and think this might be a bug which must have been introduced.

The file `~/.pm2/logs/flux-out.log` shows this:

```
2023-01-21T02:59:48: My Flux unavailability detected from 31.208.250.72
2023-01-21T02:59:48: Getting publicIp from FluxBench
2023-01-21T02:59:48: FluxBench reported the same Ip that was already in use
```
and else I also see quite often this error:

```
2023-01-21T19:00:31: TypeError: component.ports is not a function
2023-01-21T19:00:31:     at /var/home/fluxnode/zelflux/ZelBack/src/services/appsService.js:8909:21
2023-01-21T19:00:31:     at Array.forEach (<anonymous>)
2023-01-21T19:00:31:     at checkMyAppsAvailability (/var/home/fluxnode/zelflux/ZelBack/src/services/appsService.js:8908:21)
2023-01-21T19:00:31:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

The node still seems to be syncing the blocks as I can see the following log entry:

```
2023-01-21T19:01:31: Daemon Sync status: 1300803/1300803
```

but then somehow my node is not confirmed anymore as I see this log line repeating:

```
2023-01-21T19:01:39: Node not confirmed. Flux discovery is awaiting.
```
I already tried to restart my node but that did not help, I still get all the same error messages.

**To Reproduce**
I can't reproduce this as it happened on it's own during this night without me doing anything to the server.

**Expected behavior**
My node should be back online and working

**Screenshots**
n/a

**Environment(please complete the following information):**
 - OS: [Ubuntu 20.04.5 LTS]
 - Browser [Firefox]
 - Version [v3.31.2]
 - Daemon [6000050]
 - Benchmark [v3.7.2]

**Additional context**
Do not hesitate to ask me if you need further infos or logs. Thank you.

**Comment by xander2k** [comment]
I can confirm exactly the same Issue since the last update

**Comment by hostingnuggets** [comment]
Thanks @FunSkiDry, that was it! I wish these type of changes would be better communicated by the Flux team...

**Comment by TheTrunk** [comment]
Hi, 
The required ports for Flux are 16126, 16127, 16129 + reserved port 16128.  // plus 10*x eg 16146, 16147... for upnp nodes
Daemon requires outgoing port 16125.
Additionally please open flux app ports range 30000-39999

We have aleady fixed the TypoError bug you are mentioning 👍
